# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- feature/ci

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    feedsToUse: 'select'
    versioningScheme: 'off'
  displayName: 'DotNetCoreCLI build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    feedsToUse: 'select'
    versioningScheme: 'off'
  displayName: 'DotNetCoreCLI test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TEST-*.xml'
  displayName: 'PublishTestResults'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    feedsToUse: 'select'
    versioningScheme: 'off'
  displayName: 'DotNetCoreCLI publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'PublishBuildArtifacts'